# Generated by Django 5.2.10 on 2026-02-02 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessprofile',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.category'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
