# Generated by Django 5.2.10 on 2026-02-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_product_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessprofile',
            old_name='business_name',
            new_name='name',
        ),
    ]
