# Generated by Django 5.2.10 on 2026-02-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_business_name_businessprofile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessprofile',
            old_name='name',
            new_name='business_name',
        ),
    ]
