# Generated by Django 5.2.10 on 2026-02-21 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_business_name_businessprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.category'),
        ),
    ]
