# Generated by Django 5.2.10 on 2026-02-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_businessprofile_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_public',
        ),
        migrations.AddField(
            model_name='product',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
