# Generated by Django 5.2.10 on 2026-03-19 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_school_businessprofile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.school'),
            preserve_default=False,
        ),
    ]
