# Generated by Django 5.2.10 on 2026-03-25 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.category'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school'),
        ),
    ]
